### ISSUE TITLE
Problems with location

### ISSUE THREAD

**Issue by jkwok678** [ProjectRJ/BalloonApp#3]
When I copied code from the sample to the balloon app, I always get the same error.

04-06 13:20:15.502 26201-26201/com.example.admin.balloonapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.admin.balloonapp, PID: 26201
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                                  at com.example.admin.balloonapp.MainActivity.updateUI(MainActivity.java:254)
                                                                                  at com.example.admin.balloonapp.MainActivity.onConnected(MainActivity.java:328)
                                                                                  at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
                                                                                  at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
                                                                                  at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
                                                                                  at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
                                                                                  at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
                                                                                  at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jkwok678** [comment]
The results from inspecting code, this doesn't happen in the sample, only in the app we are making.

Name      public method void onConnected(Bundle connectionHint)
Location      class MainActivity (com.example.admin.balloonapp)
Problem synopsis      Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with `checkPermission`) or explicitly handle a potential `SecurityException` (at line 326)

Name      protected method void startLocationUpdates()
Location      class MainActivity (com.example.admin.balloonapp)
Problem synopsis      Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with `checkPermission`) or explicitly handle a potential `SecurityException` (at line 230)

**Comment by jkwok678** [comment]
04-06 13:40:42.909 3050-3050/com.example.admin.balloonapp I/art: Late-enabling -Xcheck:jni
04-06 13:40:42.955 3050-3050/com.example.admin.balloonapp W/System: ClassLoader referenced unknown path: /data/app/com.example.admin.balloonapp-1/lib/arm
04-06 13:40:42.977 3050-3050/com.example.admin.balloonapp I/GMPM: App measurement is starting up, version: 8487
04-06 13:40:42.977 3050-3050/com.example.admin.balloonapp I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
04-06 13:40:42.983 3050-3050/com.example.admin.balloonapp E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
04-06 13:40:42.983 3050-3050/com.example.admin.balloonapp E/GMPM: Scheduler not set. Not logging error/warn.
04-06 13:40:42.995 3050-3099/com.example.admin.balloonapp E/GMPM: Uploading is not possible. App measurement disabled
04-06 13:40:43.049 3050-3050/com.example.admin.balloonapp I/location-updates-sample: Updating values from bundle
04-06 13:40:43.049 3050-3050/com.example.admin.balloonapp I/location-updates-sample: Building GoogleApiClient
04-06 13:40:43.065 3050-3113/com.example.admin.balloonapp D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-06 13:40:43.106 3050-3113/com.example.admin.balloonapp I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-06 13:40:43.108 3050-3113/com.example.admin.balloonapp I/OpenGLRenderer: Initialized EGL, version 1.4
04-06 13:40:43.216 3050-3050/com.example.admin.balloonapp I/location-updates-sample: Connected to GoogleApiClient
04-06 13:40:43.218 3050-3050/com.example.admin.balloonapp D/AndroidRuntime: Shutting down VM
04-06 13:40:43.219 3050-3050/com.example.admin.balloonapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.admin.balloonapp, PID: 3050
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                                at com.example.admin.balloonapp.MainActivity.updateUI(MainActivity.java:254)
                                                                                at com.example.admin.balloonapp.MainActivity.onConnected(MainActivity.java:328)
                                                                                at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
                                                                                at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
                                                                                at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
                                                                                at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
                                                                                at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
                                                                                at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
                                                                                at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
                                                                                at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
                                                                                at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
                                                                                at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
                                                                                at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
