### ISSUE TITLE
App Doesn't work on all phones

### ISSUE THREAD

**Issue by jkwok678** [ProjectRJ/BalloonApp#4]
04-15 21:56:17.318 17770-17770/com.example.admin.balloonapp W/System: ClassLoader referenced unknown path: /data/app/com.example.admin.balloonapp-2/lib/arm
04-15 21:56:17.393 17770-17770/com.example.admin.balloonapp I/GMPM: App measurement is starting up, version: 8487
04-15 21:56:17.393 17770-17770/com.example.admin.balloonapp I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
04-15 21:56:17.414 17770-17770/com.example.admin.balloonapp E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
04-15 21:56:17.414 17770-17770/com.example.admin.balloonapp E/GMPM: Scheduler not set. Not logging error/warn.
04-15 21:56:17.474 17770-17817/com.example.admin.balloonapp E/GMPM: Uploading is not possible. App measurement disabled
04-15 21:56:17.790 17770-17770/com.example.admin.balloonapp I/location-updates-sample: Updating values from bundle
04-15 21:56:17.790 17770-17770/com.example.admin.balloonapp I/location-updates-sample: Building GoogleApiClient
04-15 21:56:17.872 17770-17831/com.example.admin.balloonapp W/GooglePlayServicesUtil: Google Play services out of date.  Requires 8487000 but found 8186438
04-15 21:56:17.886 17770-17832/com.example.admin.balloonapp D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-15 21:56:17.915 17770-17832/com.example.admin.balloonapp I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-15 21:56:17.916 17770-17832/com.example.admin.balloonapp I/OpenGLRenderer: Initialized EGL, version 1.4
04-15 21:56:17.948 17770-17770/com.example.admin.balloonapp I/location-updates-sample: Connection failed: ConnectionResult.getErrorCode() = 2
04-15 21:56:23.759 17770-17770/com.example.admin.balloonapp D/AndroidRuntime: Shutting down VM

```
                                                                          --------- beginning of crash
```

04-15 21:56:23.760 17770-17770/com.example.admin.balloonapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.admin.balloonapp, PID: 17770
                                                                              java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                                  at android.view.View.performClick(View.java:5204)
                                                                                  at android.view.View$PerformClick.run(View.java:21153)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                                  at android.view.View.performClick(View.java:5204) 
                                                                                  at android.view.View$PerformClick.run(View.java:21153) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
                                                                                  at com.google.android.gms.common.api.internal.zzi.zzb(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzl.zzb(Unknown Source)
                                                                                  at com.google.android.gms.common.api.internal.zzj.zzb(Unknown Source)
                                                                                  at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
                                                                                  at com.example.admin.balloonapp.MainActivity.startLocationUpdates(MainActivity.java:184)
                                                                                  at com.example.admin.balloonapp.MainActivity.startUpdatesButtonHandler(MainActivity.java:168)
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                                  at android.view.View.performClick(View.java:5204) 
                                                                                  at android.view.View$PerformClick.run(View.java:21153) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
04-15 21:56:25.597 17770-17770/com.example.admin.balloonapp I/Process: Sending signal. PID: 17770 SIG: 9

**Comment by peterfriese** [comment]
Can you please provide the version numbers of the OS and Google play Services for all phones, and indicate on which phones it works and on which it doesn't? I'd like to find out if there is an issue with the versions.

**Comment by peterfriese** [comment]
It says "GoogleApiClient not connected yet" - maybe this phone is running an outdated version of Google Play Services.

**Comment by jkwok678** [comment]
I think the issue is resolved, I just updated all the apps from the play store and that fixed it, so it might have been the Google Play Services being outdated. Thanks!
